version: "3.5"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"

  api01: &api01
    hostname: api01
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://admin:123@db:5432/rinha
    depends_on:
      - db
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api02:
    <<: *api01
    hostname: api02

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
