# @name transactions
POST http://localhost:8080/clientes/1/transacoes
Content-Type: application/json

{
    "valor": 1000,
    "tipo" : "c",
    "descricao" : "descricao"
}

###

# @name extrato
GET http://localhost:8080/clientes/1/extrato