# @name transactions
POST http://localhost:3333/clientes/2/transacoes
Content-Type: application/json

{
    "valor": 10000,
    "tipo" : "c",
    "descricao" : "Saque"
}

###

# @name extrato
GET http://localhost:3333/clientes/2/extrato